# Generated by Django 4.0 on 2021-12-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesion_id',
            new_name='question_id',
        ),
    ]
