# Generated by Django 4.0 on 2021-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_rename_quesion_id_question_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_points',
            field=models.IntegerField(default=0),
        ),
    ]
